service: hey-office-telegram

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lex:PostText"
      Resource: "*"

functions:
  webhook:
    handler: lib/handler.webhook
    events:
      - http:
          path: webhook
          method: post

resources:
  Resources:
    TelegramChatGroupTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: chatId
            AttributeType: S
        KeySchema:
          -
            AttributeName: chatId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'telegram_chat_group'
